-- 코드를 입력하세요
-- OUT 한 기억은 있는데, IN한 기억이 없다. IN엔 없고 OUT엔 있음.
SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A,
    ANIMAL_OUTS B
WHERE A.ANIMAL_ID (+)= B.ANIMAL_ID AND A.ANIMAL_ID IS NULL
ORDER BY B.ANIMAL_ID;