-- 입양을 못 간 동물 : INS에는 있지만, OUTS에는 없어야함
-- 가장 오래된 동물 3마리 : ANIMAL_INS에서 DATETIME 오름차순 상위 3개 컬럼
SELECT NAME, DATETIME
FROM (
    SELECT I.NAME, I.DATETIME
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID(+)
    WHERE O.ANIMAL_ID IS NULL
    ORDER BY I.DATETIME
)
WHERE ROWNUM <= 3